version: '3.7'

services:

  api:
   build:
     context: server
     dockerfile: services.docker
   restart: always
   ports:
    - '5001:5001'
   depends_on:
    - redis
   network_mode: "host"

  redis:
    image: 'redis:4.0-alpine'
    restart: always
    command: ["redis-server", "/etc/redis/redis.conf", "--appendonly", "yes"]
    volumes:
       - 'redis:/var/lib/redis/data'
       - ./server/workers/redis.conf:/etc/redis/redis.conf
    restart: always
    ports:
      - '6379:6379'
    network_mode: "host"

  search_triple:
    build:
      context: server
      dockerfile: search_triple.docker
    env_file:
      - server/workers/triple/triple.env
    restart: always
    network_mode: "host"

  dataprocessing:
    build:
      context: server
      dockerfile: dataprocessing.docker
    env_file:
      - server/workers/dataprocessing/dataprocessing.env
    restart: always
    network_mode: "host"
    volumes:
      - type: bind
        source: /var/opt/renv
        target: /root/.local/share/renv
      - type: bind
        source: /var/log/headstart
        target: /var/log/headstart

volumes:
  redis:
